export type Lang = 'ja' | 'en';

export type Dictionary = {
  top: {
    title: string,
    description: string,
    sprint_day: string,
    see_all: string,
    about_conference: string,
    sponsor_recruitment: string,
    speaker_recruitment: string,
    sponsor_registration: string,
    speaker_registration: string,
  },
  menu: {
    home: string,
    about: string,
    timetable: string,
    speakers: string,
    map: string,
    venue: string,
    coc: string,
    members: string,
    sponsors: string,
    coming_soon: string,
    ended: string,
    cfs: string,
    cfp: string,
    buy_ticket: string,
  },
  NavBar_About: {
    venue: string,
    coc: string,
    member: string,
    sponsor: string,
  },
  header: {
    venue: string,
  },
  footer: {
    contact_us: string,
    description: string,
    past_events: string,
  },
  members: {
    team: {
      chair: string,
      program: string,
      venue: string,
      pr: string,
      sponsor: string,
      attendee: string,
    },
    role: string,
    roles: {
      1: string,
      2: string,
      99: string,
    }
  },
  button: {
    buy_ticket: string,
  },
  venue: {
    title: string,
    title_ja: string,
    this_year_place: string,
    access_map: string,
    access_map_title: string,
    access_map_ja: string,
    hall_map: string,
    hall_map_title: string,
    hall_map_ja: string,
    overview: string,
    overview_ja: string,
    conference_name: string,
    place: string,
    place_name: string,
    expected_attendees: string,
    expected_attendees_number: string,
    holding_date_title: string,
    holding_date: string,
    address: string,
    hall_address: string,
    committee: string,
    commitee_name: string,
    head: string,
    head_name: string
    see_on_google_map: string,
  },
  timetable: {
    track: {
      'ai': string,
      'practice': string,
      'edu': string,
      'devops': string,
      'web': string,
      'libs': string,
      'core': string,
      'other': string,
      'media': string,
      'iot': string,
    }
  },
};